### ISSUE TITLE
Rolling dice macro with chat command uses chat case

### ISSUE THREAD

**Issue by tkjn** [tkjn/GameTable#46]
If you create dice macro named "DOOM", you can roll this using the following chat commands.
```
/roll DOOM
/roll doom
/roll dooM
```
However, the macro is not triggered consistently as the chat will display the case used in the chat command rather than the macros name

```
Anonymous rolls DOOM: (d6) : [1] = 1 
Anonymous rolls doom: (d6) : [5] = 5 
Anonymous rolls dooM: (d6) : [2] = 2
```

Really, I think the macro name should be displayed as it was created, regardless of the case in the chat command.

@dezzak agree?

**Comment by dezzak** [comment]
I didn't know you could do `/roll doom` but I agree it should be as
configured on the dice macro panel
